# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/james/git-repos/y4/monte-carlo-raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/james/git-repos/y4/monte-carlo-raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/git-repos/y4/monte-carlo-raytracer/CMakeFiles /home/james/git-repos/y4/monte-carlo-raytracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/git-repos/y4/monte-carlo-raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mcr

# Build rule for target.
mcr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mcr
.PHONY : mcr

# fast build rule for target.
mcr/fast:
	$(MAKE) -f CMakeFiles/mcr.dir/build.make CMakeFiles/mcr.dir/build
.PHONY : mcr/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

src/mcr.o: src/mcr.cc.o

.PHONY : src/mcr.o

# target to build an object file
src/mcr.cc.o:
	$(MAKE) -f CMakeFiles/mcr.dir/build.make CMakeFiles/mcr.dir/src/mcr.cc.o
.PHONY : src/mcr.cc.o

src/mcr.i: src/mcr.cc.i

.PHONY : src/mcr.i

# target to preprocess a source file
src/mcr.cc.i:
	$(MAKE) -f CMakeFiles/mcr.dir/build.make CMakeFiles/mcr.dir/src/mcr.cc.i
.PHONY : src/mcr.cc.i

src/mcr.s: src/mcr.cc.s

.PHONY : src/mcr.s

# target to generate assembly for a file
src/mcr.cc.s:
	$(MAKE) -f CMakeFiles/mcr.dir/build.make CMakeFiles/mcr.dir/src/mcr.cc.s
.PHONY : src/mcr.cc.s

src/sdl_window_helper.o: src/sdl_window_helper.cc.o

.PHONY : src/sdl_window_helper.o

# target to build an object file
src/sdl_window_helper.cc.o:
	$(MAKE) -f CMakeFiles/mcr.dir/build.make CMakeFiles/mcr.dir/src/sdl_window_helper.cc.o
.PHONY : src/sdl_window_helper.cc.o

src/sdl_window_helper.i: src/sdl_window_helper.cc.i

.PHONY : src/sdl_window_helper.i

# target to preprocess a source file
src/sdl_window_helper.cc.i:
	$(MAKE) -f CMakeFiles/mcr.dir/build.make CMakeFiles/mcr.dir/src/sdl_window_helper.cc.i
.PHONY : src/sdl_window_helper.cc.i

src/sdl_window_helper.s: src/sdl_window_helper.cc.s

.PHONY : src/sdl_window_helper.s

# target to generate assembly for a file
src/sdl_window_helper.cc.s:
	$(MAKE) -f CMakeFiles/mcr.dir/build.make CMakeFiles/mcr.dir/src/sdl_window_helper.cc.s
.PHONY : src/sdl_window_helper.cc.s

test/tests.o: test/tests.cc.o

.PHONY : test/tests.o

# target to build an object file
test/tests.cc.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/tests.cc.o
.PHONY : test/tests.cc.o

test/tests.i: test/tests.cc.i

.PHONY : test/tests.i

# target to preprocess a source file
test/tests.cc.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/tests.cc.i
.PHONY : test/tests.cc.i

test/tests.s: test/tests.cc.s

.PHONY : test/tests.s

# target to generate assembly for a file
test/tests.cc.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/test/tests.cc.s
.PHONY : test/tests.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... mcr"
	@echo "... run_tests"
	@echo "... src/mcr.o"
	@echo "... src/mcr.i"
	@echo "... src/mcr.s"
	@echo "... src/sdl_window_helper.o"
	@echo "... src/sdl_window_helper.i"
	@echo "... src/sdl_window_helper.s"
	@echo "... test/tests.o"
	@echo "... test/tests.i"
	@echo "... test/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

